### ISSUE TITLE
Criar um milestone chamado "Sprint 2" com a data de 20/04/2018.

### ISSUE THREAD

**Issue by tmsasaki** [luk3146/ppads-projeto-05K#9]

**Comment by luk3146** [comment]
A segunda Sprint seria, voce tem que fazer o cadastro ou fazer o login no site, após isso, você tem que clicar nos "talheres" e nisso vai aparecer "Cupons de desconto" , "lanchonetes e cupons" e "contato". Você clica ou passa o mouse encima do campo "lanchonete e cupons" que vai aparecer os restaurantes cadastrados para pegar cupom. 
Link direto da Sprint->http://18.188.27.136/mackcupons/lista_lanchonete.php?lanches=mc

PS: Tem que fazer o cadastro ou o , não se esqueça!
